// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0--rc1
// source: pkg/grpc/protos/analysis.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 推理请求
type InferRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ImageData     []byte                 `protobuf:"bytes,1,opt,name=image_data,json=imageData,proto3" json:"image_data,omitempty"`
	Width         int32                  `protobuf:"varint,2,opt,name=width,proto3" json:"width,omitempty"`
	Height        int32                  `protobuf:"varint,3,opt,name=height,proto3" json:"height,omitempty"`
	ConfThreshold float32                `protobuf:"fixed32,4,opt,name=conf_threshold,json=confThreshold,proto3" json:"conf_threshold,omitempty"`
	NmsThreshold  float32                `protobuf:"fixed32,5,opt,name=nms_threshold,json=nmsThreshold,proto3" json:"nms_threshold,omitempty"`
	ModelType     string                 `protobuf:"bytes,6,opt,name=model_type,json=modelType,proto3" json:"model_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InferRequest) Reset() {
	*x = InferRequest{}
	mi := &file_pkg_grpc_protos_analysis_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InferRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InferRequest) ProtoMessage() {}

func (x *InferRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_protos_analysis_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InferRequest.ProtoReflect.Descriptor instead.
func (*InferRequest) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_protos_analysis_proto_rawDescGZIP(), []int{0}
}

func (x *InferRequest) GetImageData() []byte {
	if x != nil {
		return x.ImageData
	}
	return nil
}

func (x *InferRequest) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *InferRequest) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *InferRequest) GetConfThreshold() float32 {
	if x != nil {
		return x.ConfThreshold
	}
	return 0
}

func (x *InferRequest) GetNmsThreshold() float32 {
	if x != nil {
		return x.NmsThreshold
	}
	return 0
}

func (x *InferRequest) GetModelType() string {
	if x != nil {
		return x.ModelType
	}
	return ""
}

// 检测框
type BoundingBox struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Label         string                 `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
	Confidence    float32                `protobuf:"fixed32,2,opt,name=confidence,proto3" json:"confidence,omitempty"`
	X1            float32                `protobuf:"fixed32,3,opt,name=x1,proto3" json:"x1,omitempty"`
	Y1            float32                `protobuf:"fixed32,4,opt,name=y1,proto3" json:"y1,omitempty"`
	X2            float32                `protobuf:"fixed32,5,opt,name=x2,proto3" json:"x2,omitempty"`
	Y2            float32                `protobuf:"fixed32,6,opt,name=y2,proto3" json:"y2,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BoundingBox) Reset() {
	*x = BoundingBox{}
	mi := &file_pkg_grpc_protos_analysis_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BoundingBox) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoundingBox) ProtoMessage() {}

func (x *BoundingBox) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_protos_analysis_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoundingBox.ProtoReflect.Descriptor instead.
func (*BoundingBox) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_protos_analysis_proto_rawDescGZIP(), []int{1}
}

func (x *BoundingBox) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *BoundingBox) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *BoundingBox) GetX1() float32 {
	if x != nil {
		return x.X1
	}
	return 0
}

func (x *BoundingBox) GetY1() float32 {
	if x != nil {
		return x.Y1
	}
	return 0
}

func (x *BoundingBox) GetX2() float32 {
	if x != nil {
		return x.X2
	}
	return 0
}

func (x *BoundingBox) GetY2() float32 {
	if x != nil {
		return x.Y2
	}
	return 0
}

// 推理响应
type InferResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Boxes         []*BoundingBox         `protobuf:"bytes,1,rep,name=boxes,proto3" json:"boxes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InferResponse) Reset() {
	*x = InferResponse{}
	mi := &file_pkg_grpc_protos_analysis_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InferResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InferResponse) ProtoMessage() {}

func (x *InferResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_protos_analysis_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InferResponse.ProtoReflect.Descriptor instead.
func (*InferResponse) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_protos_analysis_proto_rawDescGZIP(), []int{2}
}

func (x *InferResponse) GetBoxes() []*BoundingBox {
	if x != nil {
		return x.Boxes
	}
	return nil
}

var File_pkg_grpc_protos_analysis_proto protoreflect.FileDescriptor

const file_pkg_grpc_protos_analysis_proto_rawDesc = "" +
	"\n" +
	"\x1epkg/grpc/protos/analysis.proto\x12\banalysis\"\xc6\x01\n" +
	"\fInferRequest\x12\x1d\n" +
	"\n" +
	"image_data\x18\x01 \x01(\fR\timageData\x12\x14\n" +
	"\x05width\x18\x02 \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\x03 \x01(\x05R\x06height\x12%\n" +
	"\x0econf_threshold\x18\x04 \x01(\x02R\rconfThreshold\x12#\n" +
	"\rnms_threshold\x18\x05 \x01(\x02R\fnmsThreshold\x12\x1d\n" +
	"\n" +
	"model_type\x18\x06 \x01(\tR\tmodelType\"\x83\x01\n" +
	"\vBoundingBox\x12\x14\n" +
	"\x05label\x18\x01 \x01(\tR\x05label\x12\x1e\n" +
	"\n" +
	"confidence\x18\x02 \x01(\x02R\n" +
	"confidence\x12\x0e\n" +
	"\x02x1\x18\x03 \x01(\x02R\x02x1\x12\x0e\n" +
	"\x02y1\x18\x04 \x01(\x02R\x02y1\x12\x0e\n" +
	"\x02x2\x18\x05 \x01(\x02R\x02x2\x12\x0e\n" +
	"\x02y2\x18\x06 \x01(\x02R\x02y2\"<\n" +
	"\rInferResponse\x12+\n" +
	"\x05boxes\x18\x01 \x03(\v2\x15.analysis.BoundingBoxR\x05boxes2H\n" +
	"\fInferService\x128\n" +
	"\x05Infer\x12\x16.analysis.InferRequest\x1a\x17.analysis.InferResponseB\"Z\x1dgo-nvr/pkg/grpc/protos;protos\x90\x01\x01b\x06proto3"

var (
	file_pkg_grpc_protos_analysis_proto_rawDescOnce sync.Once
	file_pkg_grpc_protos_analysis_proto_rawDescData []byte
)

func file_pkg_grpc_protos_analysis_proto_rawDescGZIP() []byte {
	file_pkg_grpc_protos_analysis_proto_rawDescOnce.Do(func() {
		file_pkg_grpc_protos_analysis_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_grpc_protos_analysis_proto_rawDesc), len(file_pkg_grpc_protos_analysis_proto_rawDesc)))
	})
	return file_pkg_grpc_protos_analysis_proto_rawDescData
}

var file_pkg_grpc_protos_analysis_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_pkg_grpc_protos_analysis_proto_goTypes = []any{
	(*InferRequest)(nil),  // 0: analysis.InferRequest
	(*BoundingBox)(nil),   // 1: analysis.BoundingBox
	(*InferResponse)(nil), // 2: analysis.InferResponse
}
var file_pkg_grpc_protos_analysis_proto_depIdxs = []int32{
	1, // 0: analysis.InferResponse.boxes:type_name -> analysis.BoundingBox
	0, // 1: analysis.InferService.Infer:input_type -> analysis.InferRequest
	2, // 2: analysis.InferService.Infer:output_type -> analysis.InferResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pkg_grpc_protos_analysis_proto_init() }
func file_pkg_grpc_protos_analysis_proto_init() {
	if File_pkg_grpc_protos_analysis_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_grpc_protos_analysis_proto_rawDesc), len(file_pkg_grpc_protos_analysis_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_grpc_protos_analysis_proto_goTypes,
		DependencyIndexes: file_pkg_grpc_protos_analysis_proto_depIdxs,
		MessageInfos:      file_pkg_grpc_protos_analysis_proto_msgTypes,
	}.Build()
	File_pkg_grpc_protos_analysis_proto = out.File
	file_pkg_grpc_protos_analysis_proto_goTypes = nil
	file_pkg_grpc_protos_analysis_proto_depIdxs = nil
}
