# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: analysis.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'analysis.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x61nalysis.proto\x12\x08\x61nalysis\"\x84\x01\n\x0cInferRequest\x12\x12\n\nimage_data\x18\x01 \x01(\x0c\x12\r\n\x05width\x18\x02 \x01(\x05\x12\x0e\n\x06height\x18\x03 \x01(\x05\x12\x16\n\x0e\x63onf_threshold\x18\x04 \x01(\x02\x12\x15\n\rnms_threshold\x18\x05 \x01(\x02\x12\x12\n\nmodel_type\x18\x06 \x01(\t\"`\n\x0b\x42oundingBox\x12\r\n\x05label\x18\x01 \x01(\t\x12\x12\n\nconfidence\x18\x02 \x01(\x02\x12\n\n\x02x1\x18\x03 \x01(\x02\x12\n\n\x02y1\x18\x04 \x01(\x02\x12\n\n\x02x2\x18\x05 \x01(\x02\x12\n\n\x02y2\x18\x06 \x01(\x02\"5\n\rInferResponse\x12$\n\x05\x62oxes\x18\x01 \x03(\x0b\x32\x15.analysis.BoundingBox2H\n\x0cInferService\x12\x38\n\x05Infer\x12\x16.analysis.InferRequest\x1a\x17.analysis.InferResponseB\"Z\x1dgo-nvr/pkg/grpc/protos;protos\x90\x01\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'analysis_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\035go-nvr/pkg/grpc/protos;protos\220\001\001'
  _globals['_INFERREQUEST']._serialized_start=29
  _globals['_INFERREQUEST']._serialized_end=161
  _globals['_BOUNDINGBOX']._serialized_start=163
  _globals['_BOUNDINGBOX']._serialized_end=259
  _globals['_INFERRESPONSE']._serialized_start=261
  _globals['_INFERRESPONSE']._serialized_end=314
  _globals['_INFERSERVICE']._serialized_start=316
  _globals['_INFERSERVICE']._serialized_end=388
_builder.BuildServices(DESCRIPTOR, 'analysis_pb2', _globals)
# @@protoc_insertion_point(module_scope)
